apiVersion: v1
kind: Service
metadata:
  name: valheim-svc
spec:
  selector:
    name: valheim
  ports:
  - protocol: UDP
    name: valheim-1
    port: 2456
    targetPort: 2456
  - protocol: UDP
    name: valheim-2
    port: 2457
    targetPort: 2457
  - protocol: UDP
    name: valheim-3
    port: 2458
    targetPort: 2458
  type: LoadBalancer
